name: Test and Lint

on: [push, pull_request]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install backend dependencies
        working-directory: ./backend
        run: pip install -r requirements.txt
      
      - name: Run backend tests with coverage
        working-directory: ./backend
        run: pytest --cov=src --cov-report=term-missing
        
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Lint frontend
        working-directory: ./frontend
        run: npm run lint
      
      - name: Build frontend to check for errors
        working-directory: ./frontend
        run: npm run build 